[pytest]
addopts =
    --html=reports/test_report.html
    --self-contained-html
    --alluredir=reports/allure-results
    --junitxml=reports/junit_report.xml
    -v
    --tb=short

testpaths = Pytest-demo