name: Python Learning Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-programs:
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: Python-learning-portal/Basic

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Verify Python
        run: python --version

      - name: Show Repository Structure
        shell: cmd
        run: tree /f /a

      # === Basic Questions ===
      - name: Run Question1
        run: python Question1.py

      - name: Run Question2
        shell: cmd
        run: echo 7 | python Question2.py

      - name: Run Question3
        shell: cmd
        run: |
          (
          echo 12
          echo 18
          ) | python Question3.py

      - name: Run Question4
        shell: cmd
        run: echo Prasanna | python Question4.py

      - name: Run Question5
        shell: cmd
        run: echo 2000-06-15 | python Question5.py

      # === Medium Questions ===
      - name: Run MQuestion1
        shell: cmd
        run: |
          (
          echo 70
          echo 1.75
          ) | python MQuestion1.py

      - name: Run MQuestion2
        shell: cmd
        run: echo 950 | python MQuestion2.py

      - name: Run MQuestion3
        shell: cmd
        run: echo 4.7 | python MQuestion3.py

      - name: Run MQuestion4
        shell: cmd
        run: echo Laptop,Phone,Tablet | python MQuestion4.py

      - name: Run MQuestion5
        shell: cmd
        run: echo Hello | python MQuestion5.py

      # === Hard Questions ===
      - name: Run HQuestion1
        shell: cmd
        run: |
          (
          echo 5
          echo 90
          ) | python HQuestion1.py

      - name: Run HQuestion2
        shell: cmd
        run: |
          (
          echo 49.99
          echo 3
          ) | python HQuestion2.py

      - name: Run HQuestion3
        shell: cmd
        run: |
          (
          echo 29.99
          echo 4
          echo 200
          ) | python HQuestion3.py

      - name: Run HQuestion4
        shell: cmd
        run: |
          (
          echo 5
          echo 6
          echo 7
          ) | python HQuestion4.py

      - name: Run HQuestion5
        shell: cmd
        run: |
          (
          echo 100
          echo 2
          echo yes
          echo 50
          echo 3
          echo no
          ) | python HQuestion5.py
